services:
  postgres_db:
    restart: unless-stopped
    image: postgres:17
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_DB}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"

volumes:
  postgres_db: