services:
  postgres_db:
    restart: unless-stopped
    image: postgres:17
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  postgres_db: