"""create_pokemons_table

Revision ID: d86cc8386fb0
Revises: c7863593a773
Create Date: 2025-03-22 16:21:36.779767

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd86cc8386fb0'
down_revision: Union[str, None] = 'c7863593a773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')

    op.create_table('pokemons',
                    sa.Column('pokemon_id', sa.Uuid(as_uuid=False), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.String(length=500), nullable=True),
                    sa.Column('hp', sa.Integer(), nullable=False),
                    sa.Column('attack', sa.Integer(), nullable=False),
                    sa.Column('defense', sa.Integer(), nullable=False),
                    sa.Column('speed', sa.Integer(), nullable=False),
                    sa.Column('type',
                              sa.Enum('NORMAL', 'FIRE', 'WATER', 'ELECTRIC', 'GRASS', 'ICE', 'FIGHTING', 'POISON',
                                      'GROUND', 'FLYING', 'PSYCHIC', 'BUG', 'ROCK', 'GHOST', 'DRAGON', 'DARK', 'STEEL',
                                      'FAIRY', name='pokemontype'), nullable=False),
                    sa.Column('rarity',
                              sa.Enum('COMMON', 'UNCOMMON', 'RARE', 'LEGENDARY', 'MYTHICAL', name='pokemonrarity'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('pokemon_id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('users_pokemons',
                    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
                    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
                    sa.Column('pokemon_id', sa.Uuid(as_uuid=False), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemons.pokemon_id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    # Insert Pokémon rows
    op.execute("""
    INSERT INTO pokemons (pokemon_id, name, description, hp, attack, defense, speed, type, rarity)
    VALUES
    (uuid_generate_v4(), 'Pikachu', 'An electric mouse Pokémon', 35, 55, 40, 90, 'ELECTRIC', 'COMMON'),
    (uuid_generate_v4(), 'Charmander', 'A fire lizard Pokémon', 39, 52, 43, 65, 'FIRE', 'COMMON'),
    (uuid_generate_v4(), 'Bulbasaur', 'A grass-poison frog Pokémon', 45, 49, 49, 45, 'GRASS', 'COMMON'),
    (uuid_generate_v4(), 'Squirtle', 'A water turtle Pokémon', 44, 48, 65, 43, 'WATER', 'COMMON'),
    (uuid_generate_v4(), 'Eevee', 'A versatile Pokémon with many evolutions', 55, 40, 50, 55, 'NORMAL', 'UNCOMMON'),
    (uuid_generate_v4(), 'Jigglypuff', 'A balloon Pokémon that sings', 115, 45, 20, 20, 'FAIRY', 'UNCOMMON'),
    (uuid_generate_v4(), 'Meowth', 'A mischievous cat Pokémon', 40, 45, 35, 90, 'NORMAL', 'COMMON'),
    (uuid_generate_v4(), 'Mankey', 'A monkey Pokémon that loves to fight', 40, 80, 35, 70, 'FIGHTING', 'COMMON'),
    (uuid_generate_v4(), 'Rattata', 'A small, quick rodent Pokémon', 30, 56, 35, 72, 'NORMAL', 'COMMON'),
    (uuid_generate_v4(), 'Zubat', 'A bat Pokémon that uses echolocation', 40, 45, 35, 50, 'POISON', 'COMMON'),
    (uuid_generate_v4(), 'Pidgey', 'A small bird Pokémon', 40, 45, 40, 56, 'NORMAL', 'COMMON'),
    (uuid_generate_v4(), 'Machop', 'A strong, fighting Pokémon', 70, 80, 50, 35, 'FIGHTING', 'COMMON'),
    (uuid_generate_v4(), 'Geodude', 'A rock-ground Pokémon', 40, 80, 100, 20, 'ROCK', 'COMMON'),
    (uuid_generate_v4(), 'Onix', 'A massive rock snake Pokémon', 35, 45, 160, 70, 'ROCK', 'UNCOMMON'),
    (uuid_generate_v4(), 'Ponyta', 'A fire horse Pokémon', 50, 65, 40, 60, 'FIRE', 'UNCOMMON'),
    (uuid_generate_v4(), 'Magnemite', 'A magnetic Pokémon', 25, 35, 35, 45, 'ELECTRIC', 'UNCOMMON'),
    (uuid_generate_v4(), 'Psyduck', 'A water psychic Pokémon that has headaches', 50, 52, 48, 55, 'WATER', 'COMMON'),
    (uuid_generate_v4(), 'Golbat', 'A bat Pokémon that evolved from Zubat', 75, 80, 70, 90, 'POISON', 'UNCOMMON'),
    (uuid_generate_v4(), 'Togepi', 'A fairy type Pokémon that evolves into Togetic', 35, 20, 65, 20, 'FAIRY', 'RARE');
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_pokemons')
    op.drop_table('pokemons')
    # ### end Alembic commands ###
